# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frontend_service_edgetpu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='frontend_service_edgetpu.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x66rontend_service_edgetpu.proto\"L\n\x13InferenceRequestTPU\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\"\xd2\x01\n\x14InferenceResponseTPU\x12\x0e\n\x06output\x18\x01 \x03(\x0c\x12\x18\n\x10\x66ront_start_time\x18\x02 \x01(\x01\x12\x18\n\x10pre_process_time\x18\x03 \x01(\x01\x12\x16\n\x0etpu_start_time\x18\x04 \x01(\x01\x12\x18\n\x10tpu_process_time\x18\x05 \x01(\x01\x12\x14\n\x0ctpu_end_time\x18\x06 \x01(\x01\x12\x16\n\x0etpu_total_time\x18\x07 \x01(\x01\x12\x16\n\x0e\x66ront_end_time\x18\x08 \x01(\x01\"!\n\tGetStatus\x12\x14\n\x0cnum_requests\x18\x01 \x01(\x05\"3\n\x06Status\x12\x12\n\ninput_rate\x18\x01 \x01(\x01\x12\x15\n\rresponse_time\x18\x02 \x01(\x01\x32o\n\x12\x46rontEndServiceTPU\x12\x36\n\x05infer\x12\x14.InferenceRequestTPU\x1a\x15.InferenceResponseTPU\"\x00\x12!\n\nget_status\x12\n.GetStatus\x1a\x07.Statusb\x06proto3')
)




_INFERENCEREQUESTTPU = _descriptor.Descriptor(
  name='InferenceRequestTPU',
  full_name='InferenceRequestTPU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_name', full_name='InferenceRequestTPU.image_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='InferenceRequestTPU.image_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='InferenceRequestTPU.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=110,
)


_INFERENCERESPONSETPU = _descriptor.Descriptor(
  name='InferenceResponseTPU',
  full_name='InferenceResponseTPU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='InferenceResponseTPU.output', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_start_time', full_name='InferenceResponseTPU.front_start_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pre_process_time', full_name='InferenceResponseTPU.pre_process_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tpu_start_time', full_name='InferenceResponseTPU.tpu_start_time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tpu_process_time', full_name='InferenceResponseTPU.tpu_process_time', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tpu_end_time', full_name='InferenceResponseTPU.tpu_end_time', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tpu_total_time', full_name='InferenceResponseTPU.tpu_total_time', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='front_end_time', full_name='InferenceResponseTPU.front_end_time', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=323,
)


_GETSTATUS = _descriptor.Descriptor(
  name='GetStatus',
  full_name='GetStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_requests', full_name='GetStatus.num_requests', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=358,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_rate', full_name='Status.input_rate', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response_time', full_name='Status.response_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=411,
)

DESCRIPTOR.message_types_by_name['InferenceRequestTPU'] = _INFERENCEREQUESTTPU
DESCRIPTOR.message_types_by_name['InferenceResponseTPU'] = _INFERENCERESPONSETPU
DESCRIPTOR.message_types_by_name['GetStatus'] = _GETSTATUS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferenceRequestTPU = _reflection.GeneratedProtocolMessageType('InferenceRequestTPU', (_message.Message,), dict(
  DESCRIPTOR = _INFERENCEREQUESTTPU,
  __module__ = 'frontend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:InferenceRequestTPU)
  ))
_sym_db.RegisterMessage(InferenceRequestTPU)

InferenceResponseTPU = _reflection.GeneratedProtocolMessageType('InferenceResponseTPU', (_message.Message,), dict(
  DESCRIPTOR = _INFERENCERESPONSETPU,
  __module__ = 'frontend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:InferenceResponseTPU)
  ))
_sym_db.RegisterMessage(InferenceResponseTPU)

GetStatus = _reflection.GeneratedProtocolMessageType('GetStatus', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATUS,
  __module__ = 'frontend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:GetStatus)
  ))
_sym_db.RegisterMessage(GetStatus)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'frontend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:Status)
  ))
_sym_db.RegisterMessage(Status)



_FRONTENDSERVICETPU = _descriptor.ServiceDescriptor(
  name='FrontEndServiceTPU',
  full_name='FrontEndServiceTPU',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=413,
  serialized_end=524,
  methods=[
  _descriptor.MethodDescriptor(
    name='infer',
    full_name='FrontEndServiceTPU.infer',
    index=0,
    containing_service=None,
    input_type=_INFERENCEREQUESTTPU,
    output_type=_INFERENCERESPONSETPU,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_status',
    full_name='FrontEndServiceTPU.get_status',
    index=1,
    containing_service=None,
    input_type=_GETSTATUS,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FRONTENDSERVICETPU)

DESCRIPTOR.services_by_name['FrontEndServiceTPU'] = _FRONTENDSERVICETPU

# @@protoc_insertion_point(module_scope)
