# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend_service_edgetpu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backend_service_edgetpu.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1d\x62\x61\x63kend_service_edgetpu.proto\"e\n\nTPURequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\"U\n\x0bTPUResponse\x12\x0e\n\x06output\x18\x01 \x03(\x0c\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01\x12\x10\n\x08tpu_time\x18\x04 \x01(\x01\x32\x36\n\x0e\x42\x61\x63kEndService\x12$\n\x05infer\x12\x0b.TPURequest\x1a\x0c.TPUResponse\"\x00\x62\x06proto3')
)




_TPUREQUEST = _descriptor.Descriptor(
  name='TPURequest',
  full_name='TPURequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_name', full_name='TPURequest.image_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='TPURequest.image_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='TPURequest.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='TPURequest.model_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='TPURequest.type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=134,
)


_TPURESPONSE = _descriptor.Descriptor(
  name='TPUResponse',
  full_name='TPUResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='TPUResponse.output', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='TPUResponse.start_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='TPUResponse.end_time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tpu_time', full_name='TPUResponse.tpu_time', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=221,
)

DESCRIPTOR.message_types_by_name['TPURequest'] = _TPUREQUEST
DESCRIPTOR.message_types_by_name['TPUResponse'] = _TPURESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TPURequest = _reflection.GeneratedProtocolMessageType('TPURequest', (_message.Message,), dict(
  DESCRIPTOR = _TPUREQUEST,
  __module__ = 'backend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:TPURequest)
  ))
_sym_db.RegisterMessage(TPURequest)

TPUResponse = _reflection.GeneratedProtocolMessageType('TPUResponse', (_message.Message,), dict(
  DESCRIPTOR = _TPURESPONSE,
  __module__ = 'backend_service_edgetpu_pb2'
  # @@protoc_insertion_point(class_scope:TPUResponse)
  ))
_sym_db.RegisterMessage(TPUResponse)



_BACKENDSERVICE = _descriptor.ServiceDescriptor(
  name='BackEndService',
  full_name='BackEndService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=223,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='infer',
    full_name='BackEndService.infer',
    index=0,
    containing_service=None,
    input_type=_TPUREQUEST,
    output_type=_TPURESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKENDSERVICE)

DESCRIPTOR.services_by_name['BackEndService'] = _BACKENDSERVICE

# @@protoc_insertion_point(module_scope)
