# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import frontend_service_pb2 as frontend__service__pb2


class FrontEndServiceStub(object):
    """The FrontEnd Service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InfereImage = channel.unary_unary(
                '/FrontEndService/InfereImage',
                request_serializer=frontend__service__pb2.InferenceRequest.SerializeToString,
                response_deserializer=frontend__service__pb2.InferenceResponse.FromString,
                )


class FrontEndServiceServicer(object):
    """The FrontEnd Service definition.
    """

    def InfereImage(self, request, context):
        """Send an Inference Request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrontEndServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InfereImage': grpc.unary_unary_rpc_method_handler(
                    servicer.InfereImage,
                    request_deserializer=frontend__service__pb2.InferenceRequest.FromString,
                    response_serializer=frontend__service__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FrontEndService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrontEndService(object):
    """The FrontEnd Service definition.
    """

    @staticmethod
    def InfereImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FrontEndService/InfereImage',
            frontend__service__pb2.InferenceRequest.SerializeToString,
            frontend__service__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
